apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app1
  labels:
    app: web-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app1
  template:
    metadata:
      labels:
        app: web-app1
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: app1-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title> The first app </title>
    </head>
    <body>
        <h1> Welcome to the first App (App1) </h1>
        <p> This app works with Ingress Minikube </p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: web-app1-service
spec:
  selector:
    app: web-app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
