apiVersion: v1
kind: Service
metadata:
  name: web-nodeport-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - name: http
      protocol: TCP
      port: 80          # المنفذ الداخلي للخدمة
      targetPort: 80    # المنفذ الذي يعمل عليه الـ Pod
      nodePort: 31000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
