apiVersion: v1
kind: Pod
metadata:
  name: emptrydir-pd
spec:
  containers:
  - image: nginx
    name: nginx-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: 
      sizeLimit: 500Mi
