apiVersion: v1
kind: Pod
metadata:
  name: webapp1
  namespace: dev
  annotations:
    created-by: "abdelassit"
    description: "Test Pod"
spec:
  containers:
  - name: webapp-container
    image: nginx:alpine
    ports:
    - containerPort: 80
